<div class="container">

<table style="width: 100%;"><tr>
<td>func_error_handler</td>
<td style="text-align: right;">R Documentation</td>
</tr></table>
<h2>Custom error handler for printing the name of an enclosing function with error</h2>

<h3>Description</h3>

<p>Custom error handler for printing the name of an enclosing function with error
</p>


<h3>Usage</h3>

<pre><code class="language-R">func_error_handler(e, calling_func)
</code></pre>


<h3>Arguments</h3>

<table>
<tr style="vertical-align: top;">
<td><code>e</code></td>
<td>
<p>A <code>simpleError</code> - e.g. thrown from <code>tryCatch</code></p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>calling_func</code></td>
<td>
<p>A character string naming the enclosing function (or closure) for printing
with error messages</p>
</td>
</tr>
</table>
<h3>Value</h3>

<p>NULL - throws error with custom message
</p>


<h3>Examples</h3>

<pre><code class="language-R">## Not run: 
f &lt;- function(x) x ^ 2
tryCatch(f("a"), error = function(e) func_error_handler(e, "f"))
# Error in x^2 : non-numeric argument to binary operator
# ---&gt; called from within function: f

## End(Not run)
</code></pre>


</div>